WinRemoteAdministration/Controllers/LogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Web.Script.Serialization;
using Newtonsoft.Json;
using WinRemoteAdministration.Filters;
using WinRemoteAdministration.Models;

namespace WinRemoteAdministration.Controllers {

    /// <summary>
    /// Controller is used for handling reporting of API logs. Also handles request for statistics reports.
    /// </summary>
    [RequireLogin]
    public class LogController : Controller {
        
        /// <summary>
        /// Render View with Logs.
        /// </summary>
        /// <returns>Html page with logs.</returns>
        public ActionResult Index() {
            return View();
        }

        /// <summary>
        /// Render View with Statistics.
        /// </summary>
        /// <returns>Html page with statistics.</returns>
        public ActionResult Stats() {
            return View();
        }

        /// <summary>
        /// Process log file according to date, serialize data and return all API calls which has been made that day.
        /// </summary>
        /// <param name="date">Date of logs.</param>
        /// <returns>Json array of api calls</returns>
        public ActionResult getLog(string date) {
            var fileName = AppDomain.CurrentDomain.GetData("DataDirectory").ToString() + "/Log/" + date + ".txt";
            try {
                string file = "[" + System.IO.File.ReadAllText(fileName) + "]";
                List<ApiLogEntry> log = JsonConvert.DeserializeObject<List<ApiLogEntry>>(file);
                var iterator = 1;
                log.ToList().ForEach(x => x.Id = iterator++);
                var response = new { data = log };

                return Content(new JavaScriptSerializer().Serialize(response), "application/json");
            }
            catch (FileNotFoundException e) {
                return Json(null, JsonRequestBehavior.AllowGet);
            }
            catch (Newtonsoft.Json.JsonReaderException e) {
                return Json(null, JsonRequestBehavior.AllowGet);
            }            
        }

        /// <summary>
        /// Process log files according to date range, serialize data and return all API calls which has been made in date range.
        /// </summary>
        /// <param name="dates">Array of dates to process.</param>
        /// <returns>Json array of api calls</returns>
        public ActionResult getLogs(string[] dates) {
            List<ApiLogEntry> allLog = new List<ApiLogEntry>();

            foreach (var date in dates) {
                var fileName = AppDomain.CurrentDomain.GetData("DataDirectory").ToString() + "/Log/" + date + ".txt";
                try {
                    string file = "[" + System.IO.File.ReadAllText(fileName) + "]";
                    List<ApiLogEntry> log = JsonConvert.DeserializeObject<List<ApiLogEntry>>(file);
                    var iterator = 1;
                    log.ToList().ForEach(x => x.Id = iterator++);
                    allLog.AddRange(log);
                }
                catch (FileNotFoundException e) {}
            }

            var paramsGrouped = allLog.GroupBy(n => n.Param).
                    Select(group =>
                        new {
                            Param = group.Key,
                            Count = group.Count()
                        });

            var statusesGrouped = allLog.GroupBy(n => n.ResponseStatusCode).
                    Select(group =>
                        new {
                            Status = group.Key,
                            Count = group.Count()
                        });

            var controllersGrouped = allLog.GroupBy(n => n.Controller).
                     Select(group =>
                         new {
                             Controller = group.Key,
                             Count = group.Count()
                         });

            var actionsGrouped = allLog.GroupBy(n => n.Action).
                     Select(group =>
                         new {
                             Action = group.Key,
                             Count = group.Count()
                         });

            var usersGrouped = allLog.GroupBy(n => n.User).
                     Select(group =>
                         new {
                             User = group.Key,
                             Count = group.Count()
                         });

            var response = new {
                Params = paramsGrouped,
                Statuses = statusesGrouped,
                Actions = actionsGrouped,
                Controllers = controllersGrouped,
                Users = usersGrouped,
            };

            return Content(new JavaScriptSerializer().Serialize(response), "application/json");
        }
    }
}

WinRemoteAdministration/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Microsoft.AspNet.Identity.Owin;
using WinRemoteAdministration.Models;

namespace WinRemoteAdministration.Controllers {

    /// <summary>
    /// Processing data related to autorization of web interface users.
    /// </summary>
    public class LoginController : Controller {
        // GET: Login
        /// <summary>
        /// Render View of Login.
        /// </summary>
        /// <returns>Html page with Login form.</returns>
        public ActionResult Index() {
            return View();
        }

        /// <summary>
        /// Check if user is in supervisor role.
        /// </summary>
        /// <param name="username">Name of user.</param>
        /// <returns>Json object with true or false parameter.</returns>
        public ActionResult isSupervisor(string username) {
            AuthRepository repo = new AuthRepository();
            var Roles = repo.GetRoles(username);

            if (Roles == null) {
                return Json(new {isSupervisor = false , error = "User " + username + " is not in supervisor role."}, JsonRequestBehavior.AllowGet);
            }
            else if (Roles.Contains("supervisor")) {
                return Json(new {isSupervisor = true}, JsonRequestBehavior.AllowGet);
            }

            return Json(new { isSupervisor = false, error = "User " + username + " is not in supervisor role." }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Perform instant logout of user.
        /// </summary>
        /// <returns>Redirect user to Homepage.</returns>
        public ActionResult Logout() {
            Response.Cookies["access_token"].Expires = DateTime.Now.AddDays(-1);
            Response.Cookies["logged_user"].Expires = DateTime.Now.AddDays(-1);
            Response.Cookies["role"].Expires = DateTime.Now.AddDays(-1);

            return RedirectToAction("Index", "Home");
        }
    }
}

WinRemoteAdministration/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width"/>
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/jquery-ui.min.css")
    @Styles.Render("~/Content/jquery.dataTables.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/Scripts/js.cookie.js")
@Scripts.Render("~/Scripts/datatables.min.js")
@Scripts.Render("~/Scripts/jquery.dataTables.min.js")
@RenderSection("scripts", required: false)
<script>
    $(function() {
        $("#loading").hide();
    });

    $(document).on({
        ajaxStart: function() { $("#loading").show(); },
        ajaxStop: function() { $("#loading").hide(); }
    });
</script>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("MoWin", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Users", "Index", "Users", new {area = ""}, null)</li>
                <li>@Html.ActionLink("Logs", "Index", "Log", new {area = ""}, null)</li>
                <li>@Html.ActionLink("Statistics", "Stats", "Log", new {area = ""}, null)</li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                @if (Request.Cookies["access_token"] != null) {
                    <li>@Html.ActionLink("Logout", "Logout", "Login", new {area = ""}, null)</li>
                }
                else {
                    <li>@Html.ActionLink("Login", "Index", "Login", new {area = ""}, null)</li>
                }
            </ul>
            @if (Request.Cookies["access_token"] != null) {
                <p class="nav navbar-text navbar-right">Logged as <strong>@Request.Cookies["logged_user"].Value</strong></p>
            }
        </div>
    </div>
</div>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - MoWin</p>
    </footer>
</div>
<div id="loading"></div>
</body>
</html>